### PR TITLE
Parameters description

### PR DESCRIPTION
**Pull request by vtols**

### CODE REVIEW

**Comment by rodionos** [comment]
Do we need to wrap new values with CDATA if, for instance, new value contains XML markup characters, such as `>`?

**Comment by vtols** [comment]
Characters `& < > ' " ` are escaped before substitution into XML.

**Comment by vtols** [comment]
https://github.com/axibase/dockers/blob/atsd-sandbox/entrypoint.sh#L43-L47

**Comment by vtols** [comment]
> Each instruction should be specified in the format file_name.xml:/path/to/properties_file or file_name.xml:key1=value1,key2=value2 and will cause the attributes in the XML file to be updated with new values prior to importing the file into Collector.

This is not quite correct, because we can specify multiple config-style files for updating single XML, or mix both key-value with config file

**Comment by rodionos** [comment]
> we can specify multiple config-style files for updating single XML, or mix both key-value with config file
While potentially useful, it makes documentation somewhat more complex than needed. We can refactor the docs once we run into a use case where a combination of file and k/v will be useful.

**Pull request merged**
