### PR TITLE
Atsd sandbox update

### PR DESCRIPTION
**Pull request by vtols**
Add phantomjs, collectd and import backup

* phantomjs configuration
* Import backup archive from file or URL
* collectd configuration and start
* Collector account in ATSD
* Default account in Collector

### CODE REVIEW

**Comment by vtols** [comment]
Using environment variable `IMPORT_PATH` for now to import

- File import

```
docker run -d -p 8443:8443 -p 9443:9443 -p 8081:8081 \
--name=atsd-sandbox \ 
--volume /var/run/docker.sock:/var/run/docker.sock \
--volume /home/axibase/atsd-marathon-xml.zip:/marathon.zip \
--env IMPORT_PATH=/marathon.zip \
axibase/atsd-sandbox:latest
```

- URL import

```
docker run -d -p 8443:8443 -p 9443:9443 -p 8081:8081 \
--name=atsd-sandbox \
--volume /var/run/docker.sock:/var/run/docker.sock \
--env IMPORT_PATH=https://example.com/marathon.zip \
 axibase/atsd-sandbox:latest
```

**Comment by vtols** [comment]
File binding for import has a drawback - once file has been removed it can't restart the container anymore

**Comment by rodionos** [comment]
We need to be able to import files both into ATSD (Settings > Backup Import) and into the Collector. There could be multiple files in both cases. They be listed in the same variable using semi-colon as a separator.

**Comment by vtols** [comment]
`ATSD_IMPORT_PATH` for ATSD, `COLLECTOR_IMPORT_PATH` for Collector. Parameter for ATSD can contain only single file path or URL.

```
docker run -d -p 8443:8443 -p 9443:9443 -p 8081:8081 \
--name=atsd-sandbox \ 
--volume /var/run/docker.sock:/var/run/docker.sock \
--volume /home/axibase/atsd-marathon-xml.zip:/marathon.zip \
--volume /home/axibase/jobs.xml:/jobs.xml \
--env ATSD_IMPORT_PATH=/marathon.zip \
--env COLLECTOR_IMPORT_PATH=/jobs.xml \
axibase/atsd-sandbox:latest
```

**Pull request merged**
